### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by davidchesnut**
Some suggested changes for the readme.

### CODE REVIEW

**Comment by aafvstam** [comment]
Great work, just a few questions:

I see that Content Controls and Paragraphs have been 'lower cased'. What is the overall policy around this? I quickly checked on Docs but that wasn't always consistent either:

image

When used in code it is clear, just use the casing as an object. In text I also used Content Controls and Paragraphs cased as 'objects' but Docs used them as 'text elements' (arguably right I think). In the picture you see Document, Range, Selection and UndoRecord upper cased but always accompanied with object(s). With that I should either use "ContentControl object" (no space) or content controls, right? You probably have internal policies, are there guidelines to be found somewhere around this?

Second, minor fix I think should be changing http:// to https:// in the manifest don't you think?

In general, I'm happy with the suggested changes, it is always challenging for me as non-native writer to get around my language limitations 😉

I can merge the PR in 'as is' and change the http:// entries into https:// afterwards, what do you think?

**Comment by aafvstam** [comment]
@davidchesnut I just saw your note on my PR:
> Some minor capitalization and related changes from our style guide.

Is this style guide public?

**Comment by davidchesnut** [comment]
Yes, see https://docs.microsoft.com/en-us/style-guide/welcome/

**Comment by davidchesnut** [comment]
No worries on the "content control" capitalization. We'll help with edits as it can get tricky. In general if you are writing about the conceptual thing, it is not capitalized. If you are referring to an API name, then you use the exact capitalization from the API name and put it in `code` block. 

But yeah there are some areas that don't have a clear rule, like Office Add-ins is always capitalized. Word add-in is mixed. Thus we'll help out on editing. Don't worry about it.
Thanks!

**Comment by davidchesnut** [comment]
Yes, please change to https protocol in the manifest. Thanks!

**Pull request merged**
